/* Generated By:JJTree: Do not edit this line. ASTAndOp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAndOp extends SimpleNode {
  public ASTAndOp(int id) {
    super(id);
  }

  public ASTAndOp(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=911e4dbc0bf194f0b492d9dfaea563d8 (do not edit this line) */
