/* Generated By:JJTree: Do not edit this line. ASTExpSuffix.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpSuffix extends SimpleNode {
  public ASTExpSuffix(int id) {
    super(id);
  }

  public ASTExpSuffix(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7e2a358fb3a10012a0da91a277874027 (do not edit this line) */
