/* Generated By:JJTree: Do not edit this line. ASTIfStmnt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfStmnt extends SimpleNode {
  public ASTIfStmnt(int id) {
    super(id);
  }

  public ASTIfStmnt(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c103071cdac61ba752b4a7301e4257f9 (do not edit this line) */
