/* Generated By:JJTree: Do not edit this line. ASTParamSuffix.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParamSuffix extends SimpleNode {
  public ASTParamSuffix(int id) {
    super(id);
  }

  public ASTParamSuffix(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=38d712367dfca3f2ef5ab6bb81e01520 (do not edit this line) */
