/* Generated By:JJTree: Do not edit this line. ASTStmntSuffix.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStmntSuffix extends SimpleNode {
  public ASTStmntSuffix(int id) {
    super(id);
  }

  public ASTStmntSuffix(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fa5695328ef1a9d8325d204d0743701b (do not edit this line) */
