/* Generated By:JavaCC: Do not edit this line. Eg12Visitor.java Version 7.0.11 */
public interface Eg12Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTForStmnt node, Object data);
  public Object visit(ASTIfStmnt node, Object data);
  public Object visit(ASTElseStmnt node, Object data);
  public Object visit(ASTAssertStmnt node, Object data);
  public Object visit(ASTDeclStmnt node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTMsgStmnt node, Object data);
  public Object visit(ASTMsgSuffix node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTFunctionOrId node, Object data);
  public Object visit(ASTFunctionTail node, Object data);
  public Object visit(ASTSimExp node, Object data);
  public Object visit(ASTExpSuffix node, Object data);
  public Object visit(ASTParams node, Object data);
  public Object visit(ASTParamSuffix node, Object data);
  public Object visit(ASTLiteral node, Object data);
}
/* JavaCC - OriginalChecksum=71f804c0c2f33ce5f02f8ca5758bbbd7 (do not edit this line) */
