/* Generated By:JavaCC: Do not edit this line. Eg12TreeConstants.java Version 7.0.11 */
public interface Eg12TreeConstants
{
  public int JJTSTART = 0;
  public int JJTBLOCK = 1;
  public int JJTSTMNT = 2;
  public int JJTSTMNTSUFFIX = 3;
  public int JJTFORSTMNT = 4;
  public int JJTIFSTMNT = 5;
  public int JJTASSERTSTMNT = 6;
  public int JJTDECLSTMNT = 7;
  public int JJTEXPRESSION = 8;
  public int JJTELSE = 9;
  public int JJTMSGSTMNT = 10;
  public int JJTMSGSUFFIX = 11;
  public int JJTTYPE = 12;
  public int JJTFUNCTIONORID = 13;
  public int JJTFUNCTIONTAIL = 14;
  public int JJTSIMEXP = 15;
  public int JJTEXPSUFFIX = 16;
  public int JJTPARAMS = 17;
  public int JJTPARAMSUFFIX = 18;
  public int JJTLITERAL = 19;


  public String[] jjtNodeName = {
    "Start",
    "Block",
    "Stmnt",
    "StmntSuffix",
    "ForStmnt",
    "IfStmnt",
    "AssertStmnt",
    "DeclStmnt",
    "Expression",
    "Else",
    "MsgStmnt",
    "MsgSuffix",
    "Type",
    "FunctionOrId",
    "FunctionTail",
    "SimExp",
    "ExpSuffix",
    "Params",
    "ParamSuffix",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=918619607e94b9da21c304b81ba169ba (do not edit this line) */
