/* Generated By:JavaCC: Do not edit this line. Eg12Visitor.java Version 7.0.11 */
public interface Eg12Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTStmnt node, Object data);
  public Object visit(ASTStmntSuffix node, Object data);
  public Object visit(ASTForStmnt node, Object data);
  public Object visit(ASTIfStmnt node, Object data);
  public Object visit(ASTElseStmnt node, Object data);
  public Object visit(ASTAssertStmnt node, Object data);
  public Object visit(ASTDeclStmnt node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTMsgStmnt node, Object data);
  public Object visit(ASTMsgSuffix node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTFunctionOrId node, Object data);
  public Object visit(ASTFunctionTail node, Object data);
  public Object visit(ASTSimExp node, Object data);
  public Object visit(ASTExpSuffix node, Object data);
  public Object visit(ASTParams node, Object data);
  public Object visit(ASTParamSuffix node, Object data);
  public Object visit(ASTLiteral node, Object data);
}
/* JavaCC - OriginalChecksum=32e87694632f250faade491ec0811f49 (do not edit this line) */
