/* Generated By:JavaCC: Do not edit this line. Eg12TreeConstants.java Version 7.0.11 */
public interface Eg12TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFORSTMNT = 2;
  public int JJTIFSTMNT = 3;
  public int JJTELSESTMNT = 4;
  public int JJTASSERTSTMNT = 5;
  public int JJTDECLSTMNT = 6;
  public int JJTEXPRESSION = 7;
  public int JJTMSGSTMNT = 8;
  public int JJTMSGSUFFIX = 9;
  public int JJTFUNCTIONORID = 10;
  public int JJTFUNCTIONTAIL = 11;
  public int JJTSIMEXP = 12;
  public int JJTEXPSUFFIX = 13;
  public int JJTPARAMS = 14;
  public int JJTPARAMSUFFIX = 15;
  public int JJTLITERAL = 16;
  public int JJTIDENTIFIER = 17;
  public int JJTTYPE = 18;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "ForStmnt",
    "IfStmnt",
    "ElseStmnt",
    "AssertStmnt",
    "DeclStmnt",
    "Expression",
    "MsgStmnt",
    "MsgSuffix",
    "FunctionOrId",
    "FunctionTail",
    "SimExp",
    "ExpSuffix",
    "Params",
    "ParamSuffix",
    "Literal",
    "Identifier",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=5fa45e7c8e5b418ee17e204640b596bd (do not edit this line) */
