/* Generated By:JavaCC: Do not edit this line. Eg12DefaultVisitor.java Version 7.0.11 */
public class Eg12DefaultVisitor implements Eg12Visitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTForStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTElseStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssertStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDeclStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMsgStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMsgSuffix node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionOrId node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionTail node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSimExp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExists node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpSuffix node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAndOp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOrOp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEqOp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParams node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParamSuffix node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLiteral node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTType node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFile node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTClass node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMethod node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTField node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTString node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBool node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=31ecd0eecadb4800bc949b8bc51b0f44 (do not edit this line) */
