/* Generated By:JavaCC: Do not edit this line. Eg12TreeConstants.java Version 7.0.11 */
public interface Eg12TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFORSTMNT = 2;
  public int JJTIFSTMNT = 3;
  public int JJTELSESTMNT = 4;
  public int JJTASSERTSTMNT = 5;
  public int JJTDECLSTMNT = 6;
  public int JJTEXPRESSION = 7;
  public int JJTMSGSTMNT = 8;
  public int JJTMSGSUFFIX = 9;
  public int JJTTYPE = 10;
  public int JJTFUNCTIONORID = 11;
  public int JJTFUNCTIONTAIL = 12;
  public int JJTSIMEXP = 13;
  public int JJTEXPSUFFIX = 14;
  public int JJTPARAMS = 15;
  public int JJTPARAMSUFFIX = 16;
  public int JJTLITERAL = 17;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "ForStmnt",
    "IfStmnt",
    "ElseStmnt",
    "AssertStmnt",
    "DeclStmnt",
    "Expression",
    "MsgStmnt",
    "MsgSuffix",
    "Type",
    "FunctionOrId",
    "FunctionTail",
    "SimExp",
    "ExpSuffix",
    "Params",
    "ParamSuffix",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=ba0df5a889506a8b853b99316540fae6 (do not edit this line) */
