/* Generated By:JJTree: Do not edit this line. ASTAssertStmnt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssertStmnt extends SimpleNode {
  public ASTAssertStmnt(int id) {
    super(id);
  }

  public ASTAssertStmnt(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e19a4522d54463c725a574ac671b7ff8 (do not edit this line) */
