package parser;

/* Generated By:JJTree: Do not edit this line. ASTFunctionTail.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionTail extends SimpleNode {
  public ASTFunctionTail(int id) {
    super(id);
  }

  public ASTFunctionTail(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=85b8468f9509c97e7d59c81509b41fc9 (do not edit this line) */
