/* Generated By:JJTree: Do not edit this line. ASTMsgStmnt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMsgStmnt extends SimpleNode {
  public ASTMsgStmnt(int id) {
    super(id);
  }

  public ASTMsgStmnt(Eg12 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Eg12Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9fb4ada64134710d5d8d2e616c4ef18f (do not edit this line) */
