package parser;

/* Generated By:JavaCC: Do not edit this line. Eg12DefaultVisitor.java Version 7.0.11 */
public class Eg12DefaultVisitor implements Eg12Visitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTForStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssertStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDeclStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTElse node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMsgStmnt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionOrId node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionTail node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSimExp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParams node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=e78cbc32674e63f0af0e00e5b0160419 (do not edit this line) */
