package parser;

/* Generated By:JavaCC: Do not edit this line. Eg12TreeConstants.java Version 7.0.11 */
public interface Eg12TreeConstants
{
  public int JJTSTART = 0;
  public int JJTBLOCK = 1;
  public int JJTSTMNT = 2;
  public int JJTVOID = 3;
  public int JJTFORSTMNT = 4;
  public int JJTIFSTMNT = 5;
  public int JJTASSERTSTMNT = 6;
  public int JJTDECLSTMNT = 7;
  public int JJTEXPRESSION = 8;
  public int JJTELSE = 9;
  public int JJTMSGSTMNT = 10;
  public int JJTFUNCTIONORID = 11;
  public int JJTFUNCTIONTAIL = 12;
  public int JJTSIMEXP = 13;
  public int JJTPARAMS = 14;


  public String[] jjtNodeName = {
    "Start",
    "Block",
    "Stmnt",
    "void",
    "ForStmnt",
    "IfStmnt",
    "AssertStmnt",
    "DeclStmnt",
    "Expression",
    "Else",
    "MsgStmnt",
    "FunctionOrId",
    "FunctionTail",
    "SimExp",
    "Params",
  };
}
/* JavaCC - OriginalChecksum=2a35ffedcc41e58fd41236f9bfa2e318 (do not edit this line) */
