package parser;

/* Generated By:JavaCC: Do not edit this line. Eg12Visitor.java Version 7.0.11 */
public interface Eg12Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTStmnt node, Object data);
  public Object visit(ASTForStmnt node, Object data);
  public Object visit(ASTIfStmnt node, Object data);
  public Object visit(ASTAssertStmnt node, Object data);
  public Object visit(ASTDeclStmnt node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTElse node, Object data);
  public Object visit(ASTMsgStmnt node, Object data);
  public Object visit(ASTFunctionOrId node, Object data);
  public Object visit(ASTFunctionTail node, Object data);
  public Object visit(ASTSimExp node, Object data);
  public Object visit(ASTParams node, Object data);
}
/* JavaCC - OriginalChecksum=e8cf0eadfe2c41c528c4859e49462c7f (do not edit this line) */
